#!/bin/bash
# 手动推送到GitHub脚本

echo "===================================="
echo "推送到GitHub - 手动命令"
echo "===================================="
echo ""
echo "如果遇到SSL错误，请尝试以下方法："
echo ""
echo "方法1: 使用SSH（推荐）"
echo "--------"
echo "1. 生成SSH密钥（如果没有）:"
echo "   ssh-keygen -t ed25519 -C 'your_email@example.com'"
echo ""
echo "2. 添加公钥到GitHub:"
echo "   cat ~/.ssh/id_ed25519.pub"
echo "   # 复制输出，粘贴到 https://github.com/settings/keys"
echo ""
echo "3. 修改remote为SSH:"
echo "   git remote set-url origin git@github.com:fakechris/obsidian_vault_pipeline.git"
echo ""
echo "4. 推送:"
echo "   git push origin main"
echo ""
echo ""
echo "方法2: 使用GitHub CLI"
echo "--------"
echo "1. 安装gh:"
echo "   brew install gh"
echo ""
echo "2. 登录:"
echo "   gh auth login"
echo ""
echo "3. 推送:"
echo "   gh repo create obsidian_vault_pipeline --public --source=. --push"
echo ""
echo ""
echo "方法3: 检查网络后重试"
echo "--------"
echo "1. 测试GitHub连接:"
echo "   curl -I https://github.com"
echo ""
echo "2. 检查git配置:"
echo "   git config --global http.sslBackend"
echo "   git config --global --unset http.sslBackend  # 如果设置错误"
echo ""
echo "3. 重试推送:"
echo "   git push origin main"
echo ""
echo ""
echo "===================================="
echo "当前仓库状态:"
echo "===================================="
cd /Users/chris/Documents/openclaw-template
git log --oneline -3
echo ""
echo "远程配置:"
git remote -v
echo ""
echo "未推送提交数:"
git log origin/main..main --oneline 2>/dev/null || echo "(无法检测)"
echo ""
echo "===================================="
