from __future__ import annotations

from ..base import StageHandlerSpec


def build_stage_handlers(pack_name: str = "research-tech") -> list[StageHandlerSpec]:
    return [
        StageHandlerSpec(
            name="pinboard",
            pack=pack_name,
            handler_kind="profile_stage",
            runtime_adapter="pipeline_step",
            stage="pinboard",
            entrypoint="openclaw_pipeline.workflow_handlers:run_pipeline_pinboard",
            description="Fetch pinboard bookmarks into the inbox",
            target_mode="batch",
        ),
        StageHandlerSpec(
            name="pinboard_process",
            pack=pack_name,
            handler_kind="profile_stage",
            runtime_adapter="pipeline_step",
            stage="pinboard_process",
            entrypoint="openclaw_pipeline.workflow_handlers:run_pipeline_pinboard_process",
            description="Process fetched pinboard bookmarks",
            target_mode="batch",
        ),
        StageHandlerSpec(
            name="clippings",
            pack=pack_name,
            handler_kind="profile_stage",
            runtime_adapter="pipeline_step",
            stage="clippings",
            entrypoint="openclaw_pipeline.workflow_handlers:run_pipeline_clippings",
            description="Process local clippings into raw inbox notes",
            target_mode="batch",
        ),
        StageHandlerSpec(
            name="articles",
            pack=pack_name,
            handler_kind="profile_stage",
            runtime_adapter="pipeline_step",
            stage="articles",
            entrypoint="openclaw_pipeline.workflow_handlers:run_pipeline_articles",
            description="Generate deep dives from source notes",
            target_mode="batch",
        ),
        StageHandlerSpec(
            name="quality",
            pack=pack_name,
            handler_kind="profile_stage",
            runtime_adapter="pipeline_step",
            stage="quality",
            entrypoint="openclaw_pipeline.workflow_handlers:run_pipeline_quality",
            description="Run batch quality evaluation for deep dives",
            target_mode="batch",
        ),
        StageHandlerSpec(
            name="fix_links",
            pack=pack_name,
            handler_kind="profile_stage",
            runtime_adapter="pipeline_step",
            stage="fix_links",
            entrypoint="openclaw_pipeline.workflow_handlers:run_pipeline_fix_links",
            description="Repair broken wiki links",
            target_mode="batch",
        ),
        StageHandlerSpec(
            name="absorb",
            pack=pack_name,
            handler_kind="profile_stage",
            runtime_adapter="pipeline_step",
            stage="absorb",
            entrypoint="openclaw_pipeline.workflow_handlers:run_pipeline_absorb",
            description="Promote qualified deep dives into evergreen objects",
            target_mode="batch",
        ),
        StageHandlerSpec(
            name="registry_sync",
            pack=pack_name,
            handler_kind="profile_stage",
            runtime_adapter="pipeline_step",
            stage="registry_sync",
            entrypoint="openclaw_pipeline.workflow_handlers:run_pipeline_registry_sync",
            description="Sync the registry with the filesystem",
            target_mode="batch",
        ),
        StageHandlerSpec(
            name="moc",
            pack=pack_name,
            handler_kind="profile_stage",
            runtime_adapter="pipeline_step",
            stage="moc",
            entrypoint="openclaw_pipeline.workflow_handlers:run_pipeline_moc",
            description="Refresh atlas and MOC views",
            target_mode="batch",
        ),
        StageHandlerSpec(
            name="refine",
            pack=pack_name,
            handler_kind="profile_stage",
            runtime_adapter="pipeline_step",
            stage="refine",
            entrypoint="openclaw_pipeline.workflow_handlers:run_pipeline_refine",
            description="Run cleanup and breakdown refinement passes",
            target_mode="batch",
        ),
        StageHandlerSpec(
            name="knowledge_index",
            pack=pack_name,
            handler_kind="profile_stage",
            runtime_adapter="pipeline_step",
            stage="knowledge_index",
            entrypoint="openclaw_pipeline.workflow_handlers:run_pipeline_knowledge_index",
            description="Rebuild the derived knowledge database",
            target_mode="batch",
        ),
        StageHandlerSpec(
            name="interpretation",
            pack=pack_name,
            handler_kind="profile_stage",
            runtime_adapter="autopilot_stage",
            stage="interpretation",
            entrypoint="openclaw_pipeline.workflow_handlers:run_autopilot_interpretation",
            description="Interpret one autopilot task into a deep dive",
            target_mode="single_note",
            supports_autopilot=True,
        ),
        StageHandlerSpec(
            name="quality",
            pack=pack_name,
            handler_kind="profile_stage",
            runtime_adapter="autopilot_stage",
            stage="quality",
            entrypoint="openclaw_pipeline.workflow_handlers:run_autopilot_quality",
            description="Evaluate autopilot output quality",
            target_mode="single_note",
            supports_autopilot=True,
        ),
        StageHandlerSpec(
            name="absorb",
            pack=pack_name,
            handler_kind="profile_stage",
            runtime_adapter="autopilot_stage",
            stage="absorb",
            entrypoint="openclaw_pipeline.workflow_handlers:run_autopilot_absorb",
            description="Run absorb as an autopilot follow-up stage",
            target_mode="single_note",
            supports_autopilot=True,
        ),
        StageHandlerSpec(
            name="moc",
            pack=pack_name,
            handler_kind="profile_stage",
            runtime_adapter="autopilot_stage",
            stage="moc",
            entrypoint="openclaw_pipeline.workflow_handlers:run_autopilot_moc",
            description="Run MOC refresh as an autopilot follow-up stage",
            target_mode="single_note",
            supports_autopilot=True,
        ),
        StageHandlerSpec(
            name="refine",
            pack=pack_name,
            handler_kind="profile_stage",
            runtime_adapter="autopilot_stage",
            stage="refine",
            entrypoint="openclaw_pipeline.workflow_handlers:run_autopilot_refine",
            description="Run refine as an autopilot follow-up stage",
            target_mode="single_note",
            supports_autopilot=True,
        ),
        StageHandlerSpec(
            name="knowledge_index",
            pack=pack_name,
            handler_kind="profile_stage",
            runtime_adapter="autopilot_stage",
            stage="knowledge_index",
            entrypoint="openclaw_pipeline.workflow_handlers:run_autopilot_knowledge_index",
            description="Refresh derived truth after autopilot work",
            target_mode="single_note",
            supports_autopilot=True,
        ),
        StageHandlerSpec(
            name="deep_dive_workflow",
            pack=pack_name,
            handler_kind="focused_action",
            runtime_adapter="focused_action",
            action_kind="deep_dive_workflow",
            entrypoint="openclaw_pipeline.truth_api:_run_deep_dive_workflow_action",
            description="Create a deep dive for one processed source note",
            target_mode="single_note",
            safe_to_run=True,
            requires_truth_refresh=True,
            requires_signal_resync=True,
        ),
        StageHandlerSpec(
            name="object_extraction_workflow",
            pack=pack_name,
            handler_kind="focused_action",
            runtime_adapter="focused_action",
            action_kind="object_extraction_workflow",
            entrypoint="openclaw_pipeline.truth_api:_run_object_extraction_workflow_action",
            description="Extract evergreen objects for one deep dive",
            target_mode="single_note",
            safe_to_run=True,
            requires_truth_refresh=True,
            requires_signal_resync=True,
        ),
    ]
