//! `schedule` — PRODUCT: install a SINGLE OS entry that dispatches the job
//! registry, so the pipeline heartbeat no longer depends on a human remembering
//! to run `ovp2 daily` (M32 §9 decided OS scheduler over daemon).
//!
//! - macOS: a launchd user agent (`~/Library/LaunchAgents/com.ovp2.scheduler.plist`).
//! - Linux: a systemd user service + timer (`~/.config/systemd/user/ovp2-scheduler.*`).
//! - Anything else: a clear "not supported" error.
//!
//! The OS entry runs `ovp2 schedule tick --vault-root <v>` every
//! [`TICK_INTERVAL_SECS`]; `tick` reads `.ovp/schedule.json` (the registry) and
//! runs the jobs that are due (see [`super::scheduler`]). Each due job sources
//! the env file itself, so the unit stays trivial and credentials scope to the
//! jobs that need them. `install` seeds the registry with the default jobs
//! (daily + weekly crystallize) unless one already exists (operator edits are
//! preserved), migrates away the pre-registry `com.ovp2.daily` unit, and is
//! idempotent (unload first, overwrite, reload). `uninstall` removes the unit
//! files but leaves logs, the env file, and the registry untouched. The unit
//! files carry machine-readable `ovp2:` metadata comments that `status` parses
//! back to locate the vault + env file.

use std::path::{Path, PathBuf};

use ovp_daily::{DailyRunRecord, read_daily_ledger};

use crate::CliError;

/// launchd job label (also the plist file stem). A hand-written interim plist
/// with the same label is superseded cleanly by `install` (unload + overwrite).
pub const LAUNCHD_LABEL: &str = "com.ovp2.scheduler";
/// systemd unit stem: `ovp2-scheduler.service` + `ovp2-scheduler.timer`.
pub const SYSTEMD_UNIT: &str = "ovp2-scheduler";

/// The pre-registry label this scheduler superseded. `install` unloads/removes
/// it so an operator upgrading from the single hardwired `daily` unit does not
/// end up running two schedulers.
pub const LEGACY_LAUNCHD_LABEL: &str = "com.ovp2.daily";
pub const LEGACY_SYSTEMD_UNIT: &str = "ovp2-daily";

/// How often the single OS entry runs `schedule tick`. The tick itself decides
/// which jobs are due, so this only bounds scheduling granularity (a 09:00 job
/// fires within 10 min of 09:00).
pub const TICK_INTERVAL_SECS: u32 = 600;

const GENERATED_HEADER: &str =
    "generated by ovp2 schedule -- do not hand-edit; re-run `ovp2 schedule install`";

/// How many days without a daily run before `status` warns.
const STALE_AFTER_DAYS: i64 = 2;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ScheduleClient {
    Live,
    Replay,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Flavor {
    Launchd,
    Systemd,
}

pub struct InstallArgs {
    pub vault_root: PathBuf,
    /// Local time of day, `HH:MM` (24h).
    pub time: String,
    pub max_sources: Option<usize>,
    pub client: ScheduleClient,
    /// Env file sourced before each run. Default: `<vault>/.ovp/daily.env`.
    pub env_file: Option<PathBuf>,
    /// Pass live enrichment flags (`--web-fetch-live --github-live`).
    pub enrich: bool,
}

/// Everything the generators need, fully resolved (absolute paths, parsed time).
#[derive(Debug, Clone)]
pub struct ScheduleConfig {
    pub vault_root: PathBuf,
    pub hour: u8,
    pub minute: u8,
    pub max_sources: Option<usize>,
    pub client: ScheduleClient,
    pub env_file: PathBuf,
    pub enrich: bool,
    /// The binary the job executes — `std::env::current_exe()` at install
    /// time. Moving the binary requires re-running `install`.
    pub ovp2_path: PathBuf,
}

impl ScheduleConfig {
    pub fn time_string(&self) -> String {
        format!("{:02}:{:02}", self.hour, self.minute)
    }

    pub fn log_path(&self, flavor: Flavor) -> PathBuf {
        self.vault_root
            .join(".ovp/logs")
            .join(log_file_name(flavor))
    }
}

fn log_file_name(flavor: Flavor) -> &'static str {
    match flavor {
        Flavor::Launchd => "scheduler-launchd.log",
        Flavor::Systemd => "scheduler-systemd.log",
    }
}

// ---------------------------------------------------------------------------
// Platform + process boundary (kept behind a trait so tests never touch
// launchctl/systemctl).
// ---------------------------------------------------------------------------

pub struct RunOutput {
    pub success: bool,
    pub stdout: String,
    pub stderr: String,
}

pub trait CommandRunner {
    fn run(&self, program: &str, args: &[&str]) -> Result<RunOutput, String>;
}

pub struct SystemRunner;

impl CommandRunner for SystemRunner {
    fn run(&self, program: &str, args: &[&str]) -> Result<RunOutput, String> {
        let out = std::process::Command::new(program)
            .args(args)
            .output()
            .map_err(|e| format!("failed to run {program}: {e}"))?;
        Ok(RunOutput {
            success: out.status.success(),
            stdout: String::from_utf8_lossy(&out.stdout).into_owned(),
            stderr: String::from_utf8_lossy(&out.stderr).into_owned(),
        })
    }
}

fn detect_flavor() -> Result<Flavor, CliError> {
    if cfg!(target_os = "macos") {
        Ok(Flavor::Launchd)
    } else if cfg!(target_os = "linux") {
        Ok(Flavor::Systemd)
    } else {
        Err(CliError::Io(
            "ovp2 schedule is not supported on this platform — only macOS (launchd) \
             and Linux (systemd user timers). Run `ovp2 daily` from your own scheduler."
                .into(),
        ))
    }
}

fn home_dir() -> Result<PathBuf, CliError> {
    std::env::var_os("HOME")
        .map(PathBuf::from)
        .filter(|p| !p.as_os_str().is_empty())
        .ok_or_else(|| {
            CliError::Io("HOME is not set — cannot locate the user unit directory".into())
        })
}

/// The unit file(s) `install` writes for a flavor, under the given home dir.
/// First entry is the one `status` parses (the plist / the .service).
pub fn unit_paths(home: &Path, flavor: Flavor) -> Vec<PathBuf> {
    match flavor {
        Flavor::Launchd => vec![
            home.join("Library/LaunchAgents")
                .join(format!("{LAUNCHD_LABEL}.plist")),
        ],
        Flavor::Systemd => {
            let dir = home.join(".config/systemd/user");
            vec![
                dir.join(format!("{SYSTEMD_UNIT}.service")),
                dir.join(format!("{SYSTEMD_UNIT}.timer")),
            ]
        }
    }
}

// ---------------------------------------------------------------------------
// Pure generators
// ---------------------------------------------------------------------------

/// Parse `HH:MM` (24h). `9:30` is accepted; `24:00`, `09:60`, `0900` are not.
pub fn parse_time(s: &str) -> Result<(u8, u8), String> {
    let bad = || format!("invalid --time '{s}': expected HH:MM (24h), e.g. 09:00");
    let (h, m) = s.split_once(':').ok_or_else(bad)?;
    if h.is_empty() || h.len() > 2 || m.len() != 2 {
        return Err(bad());
    }
    let hour: u8 = h.parse().map_err(|_| bad())?;
    let minute: u8 = m.parse().map_err(|_| bad())?;
    if hour > 23 || minute > 59 {
        return Err(bad());
    }
    Ok((hour, minute))
}

/// Single-quote a string for /bin/sh.
pub fn sh_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

/// The command the OS entry runs on its interval: dispatch the registry. The
/// unit does NOT source the env file — each due job sources it itself (see
/// `scheduler::job_shell_command`), so credentials stay scoped to the jobs
/// that need them and the unit stays trivial.
pub fn tick_shell_command(cfg: &ScheduleConfig) -> String {
    format!(
        "exec {bin} schedule tick --vault-root {vault}",
        bin = sh_quote(&cfg.ovp2_path.display().to_string()),
        vault = sh_quote(&cfg.vault_root.display().to_string()),
    )
}

/// Inverse of [`xml_escape`] for metadata parsing (entities in the order
/// that can't double-decode: amp last).
fn xml_unescape(s: &str) -> String {
    s.replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", "\"")
        .replace("&apos;", "'")
        .replace("&amp;", "&")
}

pub fn xml_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

/// `ovp2:` metadata lines `status` parses back out of a generated unit file.
/// The per-job schedule lives in the registry now, so the unit only records
/// where the vault + env file are (what `status` needs to read the registry).
fn metadata_pairs(cfg: &ScheduleConfig) -> Vec<(String, String)> {
    vec![
        ("vault-root".into(), cfg.vault_root.display().to_string()),
        ("env-file".into(), cfg.env_file.display().to_string()),
    ]
}

pub fn render_launchd_plist(cfg: &ScheduleConfig) -> String {
    let mut meta = String::new();
    for (k, v) in metadata_pairs(cfg) {
        meta.push_str(&format!("<!-- ovp2:{k}={} -->\n", xml_escape(&v)));
    }
    let log = xml_escape(&cfg.log_path(Flavor::Launchd).display().to_string());
    format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- {header} -->
{meta}<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{label}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/sh</string>
        <string>-c</string>
        <string>{command}</string>
    </array>
    <key>StartInterval</key>
    <integer>{interval}</integer>
    <key>StandardOutPath</key>
    <string>{log}</string>
    <key>StandardErrorPath</key>
    <string>{log}</string>
</dict>
</plist>
"#,
        header = GENERATED_HEADER,
        meta = meta,
        label = LAUNCHD_LABEL,
        command = xml_escape(&tick_shell_command(cfg)),
        interval = TICK_INTERVAL_SECS,
        log = log,
    )
}

/// Escape one argument for a systemd `ExecStart=` line, double-quoted style:
/// backslash-escape `\` and `"`, then neutralize systemd's own `$VAR`
/// expansion (`$` → `$$`) and `%` specifiers (`%` → `%%`).
pub fn systemd_quote_arg(s: &str) -> String {
    let escaped = s
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('$', "$$")
        .replace('%', "%%");
    format!("\"{escaped}\"")
}

fn systemd_metadata(cfg: &ScheduleConfig) -> String {
    let mut meta = format!("# {GENERATED_HEADER}\n");
    for (k, v) in metadata_pairs(cfg) {
        meta.push_str(&format!("# ovp2:{k}={v}\n"));
    }
    meta
}

pub fn render_systemd_service(cfg: &ScheduleConfig) -> String {
    format!(
        "{meta}\n[Unit]\nDescription=OVP2 scheduler tick\n\n[Service]\nType=oneshot\nExecStart=/bin/sh -c {cmd}\nStandardOutput=append:{log}\nStandardError=append:{log}\n",
        meta = systemd_metadata(cfg),
        cmd = systemd_quote_arg(&tick_shell_command(cfg)),
        // systemd expands %-specifiers in path directives — a vault path
        // like /home/me/100%notes must render as 100%%notes (codex P2).
        log = cfg
            .log_path(Flavor::Systemd)
            .display()
            .to_string()
            .replace('%', "%%"),
    )
}

pub fn render_systemd_timer(cfg: &ScheduleConfig) -> String {
    // Fire every TICK_INTERVAL_SECS; `tick` decides which jobs are actually
    // due. `*:0/10` = every 10 min. Persistent catches a missed slot after the
    // machine was asleep.
    let minutes = (TICK_INTERVAL_SECS / 60).max(1);
    format!(
        "{meta}\n[Unit]\nDescription=OVP2 scheduler tick timer\n\n[Timer]\nOnCalendar=*:0/{minutes}\nPersistent=true\n\n[Install]\nWantedBy=timers.target\n",
        meta = systemd_metadata(cfg),
    )
}

/// The env-file template `install` creates when `--env-file` does not exist.
/// This file IS meant to be hand-edited (unlike the unit files) — it holds
/// the credentials the scheduled run sources.
pub fn env_template() -> String {
    "\
# generated by ovp2 schedule install -- FILL IN and keep this file chmod 600.
# Sourced (`set -a; . <this file>`) before every scheduled `ovp2 daily` run,
# so plain KEY=value lines become environment variables. Never commit it.

# Required for --client live:
#ANTHROPIC_API_KEY=sk-ant-...

# Optional LLM overrides:
#ANTHROPIC_BASE_URL=
#OVP_LLM_MODEL=
#OVP_LLM_NO_PROXY=1

# Required for --github-live enrichment of GitHub repo URLs:
#GITHUB_TOKEN=

# The 180s default mis-kills slow provider responses on live runs; keep this.
OVP_LLM_TIMEOUT_SECS=480
"
    .to_string()
}

// ---------------------------------------------------------------------------
// Pure parsers (status)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UnitMeta {
    pub vault_root: PathBuf,
    pub env_file: PathBuf,
}

/// Recover the install-time config from a generated unit file's `ovp2:`
/// metadata comments (works for both the plist and the systemd units).
pub fn parse_unit_metadata(content: &str) -> Option<UnitMeta> {
    let mut vault_root = None;
    let mut env_file = None;
    for line in content.lines() {
        let line = line.trim();
        let Some(idx) = line.find("ovp2:") else {
            continue;
        };
        let rest = line[idx + "ovp2:".len()..].trim_end_matches("-->").trim();
        let Some((key, value)) = rest.split_once('=') else {
            continue;
        };
        // Launchd metadata comments store xml-escaped values — decode so
        // `status` resolves the real filesystem paths (codex review P2).
        let value = xml_unescape(value);
        let value = value.as_str();
        match key {
            "vault-root" => vault_root = Some(PathBuf::from(value)),
            "env-file" => env_file = Some(PathBuf::from(value)),
            _ => {}
        }
    }
    Some(UnitMeta {
        vault_root: vault_root?,
        env_file: env_file?,
    })
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LaunchdJobState {
    pub loaded: bool,
    pub last_exit_status: Option<i64>,
}

/// Parse `launchctl list <label>` output. Exit failure = not loaded; on
/// success the plist-ish dump may carry `"LastExitStatus" = N;`.
pub fn parse_launchctl_list(success: bool, stdout: &str) -> LaunchdJobState {
    if !success {
        return LaunchdJobState {
            loaded: false,
            last_exit_status: None,
        };
    }
    let last_exit_status = stdout.lines().find_map(|line| {
        let line = line.trim();
        let rest = line.strip_prefix("\"LastExitStatus\"")?;
        let value = rest.trim_start_matches(|c: char| c == '=' || c.is_whitespace());
        value.trim_end_matches(';').trim().parse::<i64>().ok()
    });
    LaunchdJobState {
        loaded: true,
        last_exit_status,
    }
}

/// Latest run date in the daily ledger (ISO dates order lexicographically).
pub fn last_run_date(records: &[DailyRunRecord]) -> Option<String> {
    records.iter().map(|r| r.date.clone()).max()
}

/// Days-since-epoch for a civil date (Howard Hinnant's `days_from_civil`).
fn date_to_days(y: i64, m: i64, d: i64) -> i64 {
    let y = if m <= 2 { y - 1 } else { y };
    let era = if y >= 0 { y } else { y - 399 } / 400;
    let yoe = y - era * 400;
    let mp = (m + 9) % 12;
    let doy = (153 * mp + 2) / 5 + d - 1;
    let doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;
    era * 146_097 + doe - 719_468
}

fn parse_iso_date(s: &str) -> Option<(i64, i64, i64)> {
    let mut it = s.splitn(3, '-');
    let y = it.next()?.parse().ok()?;
    let m = it.next()?.parse().ok()?;
    let d = it.next()?.parse().ok()?;
    if !(1..=12).contains(&m) || !(1..=31).contains(&d) {
        return None;
    }
    Some((y, m, d))
}

/// Signed whole days from `a` to `b` (both `YYYY-MM-DD`).
pub fn days_between(a: &str, b: &str) -> Option<i64> {
    let (ay, am, ad) = parse_iso_date(a)?;
    let (by, bm, bd) = parse_iso_date(b)?;
    Some(date_to_days(by, bm, bd) - date_to_days(ay, am, ad))
}

/// Staleness warning when the last run is more than STALE_AFTER_DAYS old.
pub fn staleness_warning(last_run: &str, today: &str) -> Option<String> {
    let days = days_between(last_run, today)?;
    if days > STALE_AFTER_DAYS {
        Some(format!(
            "last daily run was {days} days ago (> {STALE_AFTER_DAYS}) — the queue may be \
             stalling; check the log and run `ovp2 doctor`"
        ))
    } else {
        None
    }
}

fn tail_lines(content: &str, n: usize) -> Vec<&str> {
    let lines: Vec<&str> = content.lines().filter(|l| !l.trim().is_empty()).collect();
    let start = lines.len().saturating_sub(n);
    lines[start..].to_vec()
}

// ---------------------------------------------------------------------------
// Install / uninstall (filesystem + runner; flavor and home injected for tests)
// ---------------------------------------------------------------------------

fn chmod_600(path: &Path) -> Result<(), String> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600))
            .map_err(|e| format!("chmod 600 {}: {e}", path.display()))?;
    }
    #[cfg(not(unix))]
    let _ = path;
    Ok(())
}

fn write_file_600(path: &Path, content: &str) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).map_err(|e| format!("mkdir {}: {e}", parent.display()))?;
    }
    std::fs::write(path, content).map_err(|e| format!("write {}: {e}", path.display()))?;
    chmod_600(path)
}

/// Create the env-file template if the file does not exist. Returns whether
/// it was created. An existing file is NEVER touched (it holds credentials).
pub fn ensure_env_file(path: &Path) -> Result<bool, String> {
    if path.exists() {
        return Ok(false);
    }
    write_file_600(path, &env_template())?;
    Ok(true)
}

#[derive(Debug)]
pub struct InstallReport {
    pub unit_files: Vec<PathBuf>,
    pub env_created: bool,
    /// What install did to the registry (seed vs reconcile env vs untouched).
    pub registry: RegistryOutcome,
}

/// Teardown of the pre-registry `com.ovp2.daily` unit so upgrading operators
/// don't run two schedulers — from BOTH install and uninstall, since an upgraded
/// vault may only have the old unit (codex P2). Returns the files it removed.
///
/// The unit file is removed ONLY after the OS confirms the job is no longer
/// loaded/active: if the stop command fails AND the job is still running, we
/// abort rather than orphan a live job whose file we deleted (codex P1) — a
/// failed stop for an already-stopped job is benign.
fn remove_legacy_unit(
    flavor: Flavor,
    home: &Path,
    runner: &dyn CommandRunner,
) -> Result<Vec<PathBuf>, CliError> {
    let mut removed = Vec::new();
    match flavor {
        Flavor::Launchd => {
            let plist = home
                .join("Library/LaunchAgents")
                .join(format!("{LEGACY_LAUNCHD_LABEL}.plist"));
            if plist.exists() {
                let out = runner
                    .run("launchctl", &["unload", &plist.display().to_string()])
                    .map_err(CliError::Io)?;
                if !out.success {
                    // Distinguish a real stop failure from "wasn't loaded".
                    let list = runner
                        .run("launchctl", &["list", LEGACY_LAUNCHD_LABEL])
                        .map_err(CliError::Io)?;
                    if parse_launchctl_list(list.success, &list.stdout).loaded {
                        return Err(CliError::Io(format!(
                            "legacy job {LEGACY_LAUNCHD_LABEL} is still loaded and could not be \
                             unloaded ({}); stop it by hand before installing the scheduler",
                            out.stderr.trim()
                        )));
                    }
                }
                // A leftover plist auto-loads at next login alongside the new
                // scheduler → duplicate runs, so a failed delete must fail loud.
                std::fs::remove_file(&plist)
                    .map_err(|e| CliError::Io(format!("remove legacy {}: {e}", plist.display())))?;
                removed.push(plist);
            }
        }
        Flavor::Systemd => {
            let dir = home.join(".config/systemd/user");
            let timer = dir.join(format!("{LEGACY_SYSTEMD_UNIT}.timer"));
            let service = dir.join(format!("{LEGACY_SYSTEMD_UNIT}.service"));
            if timer.exists() || service.exists() {
                let timer_unit = format!("{LEGACY_SYSTEMD_UNIT}.timer");
                let out = runner
                    .run("systemctl", &["--user", "disable", "--now", &timer_unit])
                    .map_err(CliError::Io)?;
                if !out.success {
                    let active = runner
                        .run("systemctl", &["--user", "is-active", &timer_unit])
                        .map_err(CliError::Io)?;
                    if first_word_or(&active.stdout, "") == "active" {
                        return Err(CliError::Io(format!(
                            "legacy timer {timer_unit} is still active and could not be disabled \
                             ({}); stop it by hand before installing the scheduler",
                            out.stderr.trim()
                        )));
                    }
                }
                for p in [timer, service] {
                    if p.exists() {
                        std::fs::remove_file(&p).map_err(|e| {
                            CliError::Io(format!("remove legacy {}: {e}", p.display()))
                        })?;
                        removed.push(p);
                    }
                }
            }
        }
    }
    Ok(removed)
}

/// What `ensure_registry` did to `.ovp/schedule.json`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RegistryOutcome {
    /// Written fresh with the default jobs.
    Seeded,
    /// Existed; only the install-owned `env_file` was reconciled (jobs kept).
    EnvUpdated,
    /// Existed and already matched — left untouched.
    Unchanged,
}

/// The configured env file as a registry value: `{vault}`-relative when it
/// lives under the vault (portable), absolute otherwise.
fn registry_env_value(cfg: &ScheduleConfig) -> String {
    match cfg.env_file.strip_prefix(&cfg.vault_root) {
        Ok(rel) => format!("{}/{}", super::scheduler::VAULT_PLACEHOLDER, rel.display()),
        Err(_) => cfg.env_file.display().to_string(),
    }
}

/// Ensure `.ovp/schedule.json` reflects this install. Seeds the default jobs if
/// absent; otherwise preserves operator job edits but reconciles the
/// install-owned `env_file` (a re-install with a new `--env-file` must not
/// leave the dispatcher sourcing the old credentials — codex P1).
fn ensure_registry(cfg: &ScheduleConfig) -> Result<RegistryOutcome, CliError> {
    let env_value = registry_env_value(cfg);
    if !super::scheduler::registry_path(&cfg.vault_root).exists() {
        let client = match cfg.client {
            ScheduleClient::Live => "live",
            ScheduleClient::Replay => "replay",
        };
        let mut reg = super::scheduler::default_registry(
            client,
            (cfg.hour, cfg.minute),
            cfg.enrich,
            cfg.max_sources,
        );
        reg.env_file = Some(env_value);
        super::scheduler::save_registry(&cfg.vault_root, &reg)?;
        return Ok(RegistryOutcome::Seeded);
    }
    // Existing registry: keep jobs, reconcile the install-owned env file.
    let mut reg = super::scheduler::load_registry(&cfg.vault_root)?
        .expect("registry_path exists but load returned None");
    if reg.env_file.as_deref() == Some(env_value.as_str()) {
        return Ok(RegistryOutcome::Unchanged);
    }
    reg.env_file = Some(env_value);
    super::scheduler::save_registry(&cfg.vault_root, &reg)?;
    Ok(RegistryOutcome::EnvUpdated)
}

pub fn install_with(
    cfg: &ScheduleConfig,
    flavor: Flavor,
    home: &Path,
    runner: &dyn CommandRunner,
) -> Result<InstallReport, CliError> {
    let env_created = ensure_env_file(&cfg.env_file).map_err(CliError::Io)?;
    // Hold the dispatch lock across the registry read-modify-write + state
    // seeding so a concurrent enable/disable/desktop edit can't be lost or
    // race the shared temp file (codex P2).
    let registry = {
        let _lock = super::scheduler::acquire_dispatch_lock(&cfg.vault_root)?;
        let registry = ensure_registry(cfg)?;
        // Freshly installed jobs run at their NEXT occurrence, not on the first
        // tick (codex P1) — seed state only when none exists yet.
        super::scheduler::seed_state_if_absent(&cfg.vault_root)?;
        registry
    };
    let logs_dir = cfg.vault_root.join(".ovp/logs");
    std::fs::create_dir_all(&logs_dir)
        .map_err(|e| CliError::Io(format!("mkdir {}: {e}", logs_dir.display())))?;

    let paths = unit_paths(home, flavor);
    match flavor {
        Flavor::Launchd => {
            let plist = &paths[0];
            let plist_str = plist.display().to_string();
            // Idempotency: unload whatever is loaded from this path (a
            // previous install, or the interim hand-written plist with the
            // same label). Failure just means nothing was loaded.
            let _ = runner.run("launchctl", &["unload", &plist_str]);
            write_file_600(plist, &render_launchd_plist(cfg)).map_err(CliError::Io)?;
            let out = runner
                .run("launchctl", &["load", &plist_str])
                .map_err(CliError::Io)?;
            if !out.success {
                return Err(CliError::Io(format!(
                    "launchctl load {} failed: {}",
                    plist_str,
                    out.stderr.trim()
                )));
            }
        }
        Flavor::Systemd => {
            write_file_600(&paths[0], &render_systemd_service(cfg)).map_err(CliError::Io)?;
            write_file_600(&paths[1], &render_systemd_timer(cfg)).map_err(CliError::Io)?;
            let timer = format!("{SYSTEMD_UNIT}.timer");
            for args in [
                vec!["--user", "daemon-reload"],
                vec!["--user", "enable", "--now", timer.as_str()],
            ] {
                let out = runner.run("systemctl", &args).map_err(CliError::Io)?;
                if !out.success {
                    return Err(CliError::Io(format!(
                        "systemctl {} failed: {}",
                        args.join(" "),
                        out.stderr.trim()
                    )));
                }
            }
        }
    }
    // Retire the pre-registry unit ONLY now that the new scheduler is written
    // and loaded — an earlier failure (bad registry, unwritable state, failed
    // load) must not leave the operator with no scheduler at all (codex P2).
    remove_legacy_unit(flavor, home, runner)?;
    Ok(InstallReport {
        unit_files: paths,
        env_created,
        registry,
    })
}

/// Unload/disable + remove the unit files. Logs and the env file are left
/// untouched. Returns the files actually removed (empty = nothing installed).
pub fn uninstall_with(
    flavor: Flavor,
    home: &Path,
    runner: &dyn CommandRunner,
) -> Result<Vec<PathBuf>, CliError> {
    // Tear down the pre-registry unit too — an operator who upgraded from main
    // and never re-installed only has `com.ovp2.daily`, and uninstall must not
    // leave it running (codex P2).
    let mut removed = remove_legacy_unit(flavor, home, runner)?;
    let paths = unit_paths(home, flavor);
    let installed: Vec<&PathBuf> = paths.iter().filter(|p| p.exists()).collect();
    if installed.is_empty() {
        return Ok(removed);
    }
    match flavor {
        Flavor::Launchd => {
            // Best-effort unload; the file may exist without being loaded.
            let _ = runner.run("launchctl", &["unload", &paths[0].display().to_string()]);
        }
        Flavor::Systemd => {
            let timer = format!("{SYSTEMD_UNIT}.timer");
            let _ = runner.run("systemctl", &["--user", "disable", "--now", &timer]);
        }
    }
    for p in installed {
        std::fs::remove_file(p)
            .map_err(|e| CliError::Io(format!("remove {}: {e}", p.display())))?;
        removed.push(p.clone());
    }
    if flavor == Flavor::Systemd {
        let _ = runner.run("systemctl", &["--user", "daemon-reload"]);
    }
    Ok(removed)
}

// ---------------------------------------------------------------------------
// CLI entry points
// ---------------------------------------------------------------------------

fn absolutize(p: PathBuf) -> Result<PathBuf, CliError> {
    if p.is_absolute() {
        Ok(p)
    } else {
        std::env::current_dir()
            .map(|cwd| cwd.join(p))
            .map_err(|e| CliError::Io(format!("cannot resolve current dir: {e}")))
    }
}

pub fn run_install(args: InstallArgs) -> Result<(), CliError> {
    let flavor = detect_flavor()?;
    let home = home_dir()?;
    let (hour, minute) = parse_time(&args.time).map_err(CliError::Io)?;
    let vault_root = args.vault_root.canonicalize().map_err(|e| {
        CliError::Io(format!(
            "vault root {} is not usable: {e}",
            args.vault_root.display()
        ))
    })?;
    let env_file = match args.env_file {
        Some(p) => absolutize(p)?,
        None => vault_root.join(".ovp/daily.env"),
    };
    let ovp2_path = std::env::current_exe()
        .map_err(|e| CliError::Io(format!("cannot resolve the ovp2 binary path: {e}")))?;
    let cfg = ScheduleConfig {
        vault_root,
        hour,
        minute,
        max_sources: args.max_sources,
        client: args.client,
        env_file,
        enrich: args.enrich,
        ovp2_path,
    };

    let report = install_with(&cfg, flavor, &home, &SystemRunner)?;

    println!("schedule installed ({})", flavor_name(flavor));
    for p in &report.unit_files {
        println!("  unit:      {}", p.display());
    }
    println!(
        "  runs:      scheduler tick every {} min (dispatches due jobs)",
        TICK_INTERVAL_SECS / 60
    );
    let reg_path = super::scheduler::registry_path(&cfg.vault_root).display().to_string();
    match report.registry {
        RegistryOutcome::Seeded => {
            println!("  registry:  {reg_path} (NEW — daily {} + weekly crystallize)", cfg.time_string());
            println!("             edit it or use `ovp2 schedule enable/disable <id>`");
        }
        RegistryOutcome::EnvUpdated => {
            println!("  registry:  {reg_path} (existing jobs kept; env-file updated)");
        }
        RegistryOutcome::Unchanged => {
            println!("  registry:  {reg_path} (existing, left untouched)");
        }
    }
    println!("  vault:     {}", cfg.vault_root.display());
    println!("  binary:    {}", cfg.ovp2_path.display());
    println!("  log:       {}", cfg.log_path(flavor).display());
    if report.env_created {
        println!(
            "  env-file:  {} (NEW template, chmod 600)",
            cfg.env_file.display()
        );
        println!(
            "             fill in ANTHROPIC_API_KEY (required for --client live); optional:\n\
             \x20            ANTHROPIC_BASE_URL, OVP_LLM_MODEL, OVP_LLM_NO_PROXY, GITHUB_TOKEN"
        );
    } else {
        println!(
            "  env-file:  {} (existing, left untouched)",
            cfg.env_file.display()
        );
    }
    println!(
        "  note:      the job pins this binary path — re-run `ovp2 schedule install`\n\
         \x20            after moving the binary (brew upgrades keep the path stable)."
    );
    println!("  check:     ovp2 schedule status  ·  jobs: ovp2 schedule list --vault-root <v>");
    Ok(())
}

pub fn run_uninstall() -> Result<(), CliError> {
    let flavor = detect_flavor()?;
    let home = home_dir()?;
    let removed = uninstall_with(flavor, &home, &SystemRunner)?;
    if removed.is_empty() {
        println!(
            "schedule: nothing installed ({}) — nothing to remove",
            flavor_name(flavor)
        );
    } else {
        println!("schedule uninstalled ({})", flavor_name(flavor));
        for p in removed {
            println!("  removed:   {}", p.display());
        }
        println!("  kept:      logs and the env file (remove by hand if unwanted)");
    }
    Ok(())
}

pub fn run_status(today: &str) -> Result<(), CliError> {
    let flavor = detect_flavor()?;
    let home = home_dir()?;
    status_with(flavor, &home, &SystemRunner, today)
}

fn flavor_name(flavor: Flavor) -> &'static str {
    match flavor {
        Flavor::Launchd => "launchd",
        Flavor::Systemd => "systemd user timer",
    }
}

fn status_with(
    flavor: Flavor,
    home: &Path,
    runner: &dyn CommandRunner,
    today: &str,
) -> Result<(), CliError> {
    let paths = unit_paths(home, flavor);
    let unit = &paths[0];
    println!("schedule status ({})", flavor_name(flavor));
    if !unit.exists() {
        println!("  not installed — run: ovp2 schedule install --vault-root <vault>");
        return Ok(());
    }
    println!("  unit:      {}", unit.display());

    // Loaded / enabled state from the OS scheduler.
    match flavor {
        Flavor::Launchd => {
            let out = runner
                .run("launchctl", &["list", LAUNCHD_LABEL])
                .map_err(CliError::Io)?;
            let state = parse_launchctl_list(out.success, &out.stdout);
            if state.loaded {
                match state.last_exit_status {
                    Some(code) => println!("  loaded:    yes (last exit status {code})"),
                    None => println!("  loaded:    yes"),
                }
            } else {
                println!("  loaded:    NO — re-run `ovp2 schedule install`");
            }
        }
        Flavor::Systemd => {
            let timer = format!("{SYSTEMD_UNIT}.timer");
            let enabled = runner
                .run("systemctl", &["--user", "is-enabled", &timer])
                .map_err(CliError::Io)?;
            let active = runner
                .run("systemctl", &["--user", "is-active", &timer])
                .map_err(CliError::Io)?;
            println!(
                "  timer:     {} / {}",
                first_word_or(&enabled.stdout, "unknown"),
                first_word_or(&active.stdout, "unknown")
            );
            if !enabled.success || !active.success {
                println!("             not fully enabled — re-run `ovp2 schedule install`");
            }
        }
    }

    // Install-time config, recovered from the unit file's metadata comments.
    let content = std::fs::read_to_string(unit)
        .map_err(|e| CliError::Io(format!("read {}: {e}", unit.display())))?;
    let Some(meta) = parse_unit_metadata(&content) else {
        println!(
            "  WARN: unit file has no ovp2 metadata (hand-edited?) — re-run `ovp2 schedule install`"
        );
        return Ok(());
    };
    println!(
        "  tick:      every {} min (jobs live in the registry)",
        TICK_INTERVAL_SECS / 60
    );
    println!("  vault:     {}", meta.vault_root.display());
    let env_state = if meta.env_file.exists() {
        "present"
    } else {
        "MISSING"
    };
    println!("  env-file:  {} ({env_state})", meta.env_file.display());
    // The per-job schedule (cadences, last run, next due, "due now") lives in
    // the registry — render it here so `status` reflects failed/overdue jobs a
    // no-op tick's exit code would otherwise have masked (codex P2).
    let reg_path = super::scheduler::registry_path(&meta.vault_root);
    println!("  registry:  {}", reg_path.display());
    match super::scheduler::load_registry(&meta.vault_root) {
        Ok(Some(reg)) => match super::scheduler::load_state(&meta.vault_root) {
            Ok(state) => {
                super::scheduler::print_jobs(&reg, &state, super::scheduler::local_now(), "  ")
            }
            // A malformed state file blocks `tick`, so surface it rather than
            // silently showing every job as never-run/due-now (codex P2).
            Err(e) => println!("             WARN: cannot read schedule state: {e}"),
        },
        Ok(None) => println!("             MISSING — re-run `ovp2 schedule install`"),
        Err(e) => println!("             WARN: cannot read registry: {e}"),
    }

    // Last log lines.
    let log = meta
        .vault_root
        .join(".ovp/logs")
        .join(log_file_name(flavor));
    match std::fs::read_to_string(&log) {
        Ok(text) => {
            println!("  log:       {}", log.display());
            for line in tail_lines(&text, 5) {
                println!("    | {line}");
            }
        }
        Err(_) => println!("  log:       {} (no log yet)", log.display()),
    }

    // Last run — PREFER the run-liveness heartbeat (`.ovp/last-run.json`, OVP2
    // observability P0): it carries the terminal status of the most recent run,
    // so an unattended run that FAILED or ABORTED before writing a report is
    // still surfaced here. The append-only ledger's date is the fallback for a
    // vault whose last successful run predates the heartbeat.
    match ovp_daily::read_last_run(&meta.vault_root) {
        Ok(Some(hb)) => {
            let when = hb.ended_at.as_deref().unwrap_or(hb.started_at.as_str());
            let status = match hb.status {
                ovp_daily::LastRunStatus::Completed => "completed",
                ovp_daily::LastRunStatus::Failed => "FAILED",
                ovp_daily::LastRunStatus::Aborted => "ABORTED",
                ovp_daily::LastRunStatus::Running => "running",
            };
            println!("  last run:  {status} at {when} ({})", hb.run_id);
            match hb.status {
                ovp_daily::LastRunStatus::Failed | ovp_daily::LastRunStatus::Aborted => {
                    println!(
                        "  WARN: the last run did not complete ({status}){} — check the schedule log and rerun `ovp2 daily`",
                        hb.error.as_deref().map(|e| format!(": {e}")).unwrap_or_default()
                    );
                }
                _ => {}
            }
        }
        Ok(None) => report_last_run_from_ledger(&meta.vault_root, today),
        Err(e) => {
            println!("  WARN: cannot read .ovp/last-run.json: {e}");
            report_last_run_from_ledger(&meta.vault_root, today);
        }
    }
    Ok(())
}

/// Fallback last-run report from the append-only daily ledger (date only; no
/// terminal status), used when the heartbeat file is absent or unreadable.
fn report_last_run_from_ledger(vault_root: &Path, today: &str) {
    let ledger_path = vault_root.join(".ovp/daily-runs.jsonl");
    match read_daily_ledger(&ledger_path) {
        Ok(records) => match last_run_date(&records) {
            Some(last) => {
                let ago = days_between(&last, today)
                    .map(|d| format!(" ({d} day(s) ago)"))
                    .unwrap_or_default();
                println!("  last run:  {last}{ago}");
                if let Some(warn) = staleness_warning(&last, today) {
                    println!("  WARN: {warn}");
                }
            }
            None => println!("  last run:  never (empty ledger)"),
        },
        Err(e) => println!("  WARN: cannot read {}: {e}", ledger_path.display()),
    }
}

fn first_word_or<'a>(s: &'a str, fallback: &'a str) -> &'a str {
    let w = s.trim();
    if w.is_empty() {
        fallback
    } else {
        w.lines().next().unwrap_or(fallback)
    }
}

// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::cell::RefCell;

    fn cfg() -> ScheduleConfig {
        ScheduleConfig {
            vault_root: PathBuf::from("/Users/op/ovp-vault"),
            hour: 9,
            minute: 0,
            max_sources: None,
            client: ScheduleClient::Live,
            env_file: PathBuf::from("/Users/op/ovp-vault/.ovp/daily.env"),
            enrich: true,
            ovp2_path: PathBuf::from("/opt/homebrew/bin/ovp2"),
        }
    }

    #[derive(Default)]
    struct FakeRunner {
        calls: RefCell<Vec<String>>,
        fail_all: bool,
    }

    impl CommandRunner for FakeRunner {
        fn run(&self, program: &str, args: &[&str]) -> Result<RunOutput, String> {
            self.calls
                .borrow_mut()
                .push(format!("{program} {}", args.join(" ")));
            Ok(RunOutput {
                success: !self.fail_all,
                stdout: String::new(),
                stderr: "boom".into(),
            })
        }
    }

    // -- arg validation -----------------------------------------------------

    #[test]
    fn parse_time_accepts_valid_forms() {
        assert_eq!(parse_time("09:00").unwrap(), (9, 0));
        assert_eq!(parse_time("9:30").unwrap(), (9, 30));
        assert_eq!(parse_time("23:59").unwrap(), (23, 59));
        assert_eq!(parse_time("00:00").unwrap(), (0, 0));
    }

    #[test]
    fn parse_time_rejects_garbage() {
        for bad in [
            "", "0900", "24:00", "12:60", "ab:cd", "12:5", "12:005", "-1:00",
        ] {
            assert!(parse_time(bad).is_err(), "{bad} should be rejected");
        }
    }

    #[test]
    fn sh_quote_handles_single_quotes() {
        assert_eq!(sh_quote("/a/b"), "'/a/b'");
        assert_eq!(sh_quote("it's"), "'it'\\''s'");
    }

    // -- shell command ------------------------------------------------------

    #[test]
    fn tick_command_execs_scheduler_tick() {
        // The unit dispatches the registry; it does NOT source env or run
        // `daily` directly (each due job sources env itself).
        let cmd = tick_shell_command(&cfg());
        assert_eq!(
            cmd,
            "exec '/opt/homebrew/bin/ovp2' schedule tick --vault-root '/Users/op/ovp-vault'"
        );
        assert!(!cmd.contains("set -a"), "unit must not source env");
        assert!(!cmd.contains("--date"), "date is per-job, not per-tick");
    }

    // -- launchd plist ------------------------------------------------------

    #[test]
    fn plist_carries_label_interval_logs_and_header() {
        let plist = render_launchd_plist(&cfg());
        assert!(plist.contains("<string>com.ovp2.scheduler</string>"));
        assert!(plist.contains("<string>/bin/sh</string>"));
        assert!(plist.contains("<string>-c</string>"));
        // Interval-based, not a fixed calendar time (the tick decides due jobs).
        assert!(
            plist.contains(&format!(
                "<key>StartInterval</key>\n    <integer>{TICK_INTERVAL_SECS}</integer>"
            )),
            "got: {plist}"
        );
        assert!(!plist.contains("StartCalendarInterval"));
        assert!(
            plist.contains("<string>/Users/op/ovp-vault/.ovp/logs/scheduler-launchd.log</string>")
        );
        assert!(plist.contains(GENERATED_HEADER));
        assert!(plist.contains("schedule tick --vault-root"));
    }

    #[test]
    fn plist_xml_escapes_paths() {
        let mut c = cfg();
        c.vault_root = PathBuf::from("/Users/op/a&b");
        c.env_file = PathBuf::from("/Users/op/a&b/.ovp/daily.env");
        let plist = render_launchd_plist(&c);
        assert!(plist.contains("a&amp;b"));
        assert!(!plist.contains("a&b/"), "raw & must not survive: {plist}");
    }

    // -- systemd units ------------------------------------------------------

    #[test]
    fn systemd_service_runs_tick_oneshot() {
        let svc = render_systemd_service(&cfg());
        assert!(svc.contains("ExecStart=/bin/sh -c \"exec"));
        assert!(svc.contains("schedule tick --vault-root"));
        assert!(svc.contains("Type=oneshot"));
        assert!(svc
            .contains("StandardOutput=append:/Users/op/ovp-vault/.ovp/logs/scheduler-systemd.log"));
        assert!(svc
            .contains("StandardError=append:/Users/op/ovp-vault/.ovp/logs/scheduler-systemd.log"));
        assert!(svc.starts_with(&format!("# {GENERATED_HEADER}")));
    }

    #[test]
    fn systemd_timer_fires_on_interval_and_persistent() {
        let timer = render_systemd_timer(&cfg());
        let minutes = (TICK_INTERVAL_SECS / 60).max(1);
        assert!(timer.contains(&format!("OnCalendar=*:0/{minutes}")), "got: {timer}");
        assert!(!timer.contains("*-*-*"), "no fixed calendar time anymore");
        assert!(timer.contains("Persistent=true"));
        assert!(timer.contains("WantedBy=timers.target"));
        assert!(timer.contains(GENERATED_HEADER));
    }

    // -- env template -------------------------------------------------------

    #[test]
    fn env_template_lists_credentials_commented() {
        let t = env_template();
        for key in [
            "#ANTHROPIC_API_KEY=",
            "#ANTHROPIC_BASE_URL=",
            "#OVP_LLM_MODEL=",
            "#GITHUB_TOKEN=",
        ] {
            assert!(t.contains(key), "missing {key}");
        }
        assert!(t.contains("OVP_LLM_TIMEOUT_SECS=480"));
    }

    #[test]
    fn ensure_env_file_creates_template_but_never_overwrites() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(".ovp/daily.env");
        assert!(ensure_env_file(&path).unwrap(), "first call creates");
        assert_eq!(std::fs::read_to_string(&path).unwrap(), env_template());
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(&path).unwrap().permissions().mode();
            assert_eq!(mode & 0o777, 0o600, "env file must be chmod 600");
        }
        std::fs::write(&path, "ANTHROPIC_API_KEY=secret\n").unwrap();
        assert!(!ensure_env_file(&path).unwrap(), "existing file untouched");
        assert_eq!(
            std::fs::read_to_string(&path).unwrap(),
            "ANTHROPIC_API_KEY=secret\n"
        );
    }

    // -- metadata round-trip ------------------------------------------------

    #[test]
    fn unit_metadata_round_trips_from_both_flavors() {
        let expected = UnitMeta {
            vault_root: PathBuf::from("/Users/op/ovp-vault"),
            env_file: PathBuf::from("/Users/op/ovp-vault/.ovp/daily.env"),
        };
        assert_eq!(
            parse_unit_metadata(&render_launchd_plist(&cfg())).unwrap(),
            expected
        );
        assert_eq!(
            parse_unit_metadata(&render_systemd_service(&cfg())).unwrap(),
            expected
        );
    }

    #[test]
    fn xml_entities_in_metadata_round_trip() {
        // Paths with XML-sensitive characters must decode back to the real
        // filesystem path when status parses launchd metadata (codex P2).
        let mut c = cfg();
        c.vault_root = PathBuf::from("/Users/op/A&B <vault>");
        c.env_file = PathBuf::from("/Users/op/A&B <vault>/.ovp/daily.env");
        let plist = render_launchd_plist(&c);
        let meta = parse_unit_metadata(&plist).expect("metadata parses");
        assert_eq!(meta.vault_root, PathBuf::from("/Users/op/A&B <vault>"));
    }

    #[test]
    fn systemd_log_paths_escape_percent_specifiers() {
        let mut c = cfg();
        c.vault_root = PathBuf::from("/home/me/100%notes");
        c.env_file = PathBuf::from("/home/me/100%notes/.ovp/daily.env");
        let svc = render_systemd_service(&c);
        assert!(svc.contains("StandardOutput=append:/home/me/100%%notes/"));
        assert!(!svc.contains("append:/home/me/100%notes/"));
    }

    #[test]
    fn unit_metadata_missing_keys_is_none() {
        assert_eq!(parse_unit_metadata("<plist>hand-written</plist>"), None);
        assert_eq!(parse_unit_metadata("# ovp2:time=09:00\n"), None);
    }

    // -- status parsing -----------------------------------------------------

    #[test]
    fn launchctl_list_parses_loaded_and_exit_status() {
        let out = "{\n\t\"Label\" = \"com.ovp2.daily\";\n\t\"LastExitStatus\" = 0;\n};\n";
        assert_eq!(
            parse_launchctl_list(true, out),
            LaunchdJobState {
                loaded: true,
                last_exit_status: Some(0)
            }
        );
        assert_eq!(
            parse_launchctl_list(false, ""),
            LaunchdJobState {
                loaded: false,
                last_exit_status: None
            }
        );
        assert_eq!(
            parse_launchctl_list(true, "{ \"Label\" = \"com.ovp2.daily\"; };"),
            LaunchdJobState {
                loaded: true,
                last_exit_status: None
            }
        );
    }

    #[test]
    fn staleness_warns_only_after_two_days() {
        assert_eq!(staleness_warning("2026-07-07", "2026-07-07"), None);
        assert_eq!(staleness_warning("2026-07-05", "2026-07-07"), None);
        assert!(staleness_warning("2026-07-04", "2026-07-07").is_some());
        // month + year boundaries
        assert!(staleness_warning("2025-12-31", "2026-01-03").is_some());
        assert_eq!(staleness_warning("2026-06-30", "2026-07-02"), None);
    }

    #[test]
    fn tail_lines_takes_last_nonempty() {
        let text = "a\nb\n\nc\nd\ne\nf\n";
        assert_eq!(tail_lines(text, 5), vec!["b", "c", "d", "e", "f"]);
        assert_eq!(tail_lines("x\n", 5), vec!["x"]);
    }

    // -- install / uninstall (fake runner; no real launchctl/systemctl) ------

    #[test]
    fn install_launchd_writes_plist_and_reloads() {
        let home = tempfile::tempdir().unwrap();
        let vault = tempfile::tempdir().unwrap();
        let mut c = cfg();
        c.vault_root = vault.path().to_path_buf();
        c.env_file = vault.path().join(".ovp/daily.env");
        let runner = FakeRunner::default();

        let report = install_with(&c, Flavor::Launchd, home.path(), &runner).unwrap();

        let plist = home
            .path()
            .join("Library/LaunchAgents/com.ovp2.scheduler.plist");
        assert_eq!(report.unit_files, vec![plist.clone()]);
        assert!(report.env_created);
        assert_eq!(report.registry, RegistryOutcome::Seeded, "install seeds the registry");
        assert!(
            super::super::scheduler::registry_path(vault.path()).exists(),
            "schedule.json written"
        );
        assert!(plist.exists());
        assert!(c.env_file.exists());
        assert!(vault.path().join(".ovp/logs").is_dir());
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(&plist).unwrap().permissions().mode();
            assert_eq!(mode & 0o777, 0o600, "plist must be chmod 600");
        }
        let calls = runner.calls.borrow();
        assert_eq!(
            *calls,
            vec![
                format!("launchctl unload {}", plist.display()),
                format!("launchctl load {}", plist.display()),
            ]
        );
    }

    #[test]
    fn reinstall_overwrites_unit_but_keeps_env_and_registry() {
        let home = tempfile::tempdir().unwrap();
        let vault = tempfile::tempdir().unwrap();
        let mut c = cfg();
        c.vault_root = vault.path().to_path_buf();
        c.env_file = vault.path().join(".ovp/daily.env");
        let runner = FakeRunner::default();
        install_with(&c, Flavor::Launchd, home.path(), &runner).unwrap();
        std::fs::write(&c.env_file, "ANTHROPIC_API_KEY=secret\n").unwrap();
        // Operator hand-edits the registry (disables crystallize).
        let reg_path = super::super::scheduler::registry_path(vault.path());
        let mut reg = super::super::scheduler::load_registry(vault.path())
            .unwrap()
            .unwrap();
        reg.get_mut("crystallize").unwrap().enabled = false;
        super::super::scheduler::save_registry(vault.path(), &reg).unwrap();

        c.hour = 21; // re-install with a new time
        let report = install_with(&c, Flavor::Launchd, home.path(), &runner).unwrap();

        assert!(!report.env_created);
        // Same env file -> registry left untouched.
        assert_eq!(report.registry, RegistryOutcome::Unchanged);
        assert_eq!(
            std::fs::read_to_string(&c.env_file).unwrap(),
            "ANTHROPIC_API_KEY=secret\n"
        );
        // The operator's edit survives (re-install did NOT clobber the registry).
        let reg2 = super::super::scheduler::load_registry(vault.path())
            .unwrap()
            .unwrap();
        assert!(!reg2.get("crystallize").unwrap().enabled);
        assert!(reg_path.exists());
        // The unit is interval-based (no per-time integer to check).
        let plist = std::fs::read_to_string(&report.unit_files[0]).unwrap();
        assert!(plist.contains("StartInterval"));
    }

    #[test]
    fn reinstall_with_new_env_file_reconciles_registry_but_keeps_jobs() {
        let home = tempfile::tempdir().unwrap();
        let vault = tempfile::tempdir().unwrap();
        let mut c = cfg();
        c.vault_root = vault.path().to_path_buf();
        c.env_file = vault.path().join(".ovp/daily.env");
        let runner = FakeRunner::default();
        install_with(&c, Flavor::Launchd, home.path(), &runner).unwrap();
        // Operator disables a job.
        let mut reg = super::super::scheduler::load_registry(vault.path())
            .unwrap()
            .unwrap();
        reg.get_mut("crystallize").unwrap().enabled = false;
        super::super::scheduler::save_registry(vault.path(), &reg).unwrap();

        // Re-install pointing at a NEW env file (credential rotation).
        c.env_file = vault.path().join(".ovp/rotated.env");
        let report = install_with(&c, Flavor::Launchd, home.path(), &runner).unwrap();

        assert_eq!(report.registry, RegistryOutcome::EnvUpdated);
        let reg2 = super::super::scheduler::load_registry(vault.path())
            .unwrap()
            .unwrap();
        // env file reconciled...
        assert_eq!(
            reg2.env_file.as_deref(),
            Some("{vault}/.ovp/rotated.env")
        );
        // ...but the operator's job edit is preserved.
        assert!(!reg2.get("crystallize").unwrap().enabled);
    }

    #[test]
    fn install_systemd_writes_units_and_enables_timer() {
        let home = tempfile::tempdir().unwrap();
        let vault = tempfile::tempdir().unwrap();
        let mut c = cfg();
        c.vault_root = vault.path().to_path_buf();
        c.env_file = vault.path().join(".ovp/daily.env");
        let runner = FakeRunner::default();

        let report = install_with(&c, Flavor::Systemd, home.path(), &runner).unwrap();

        let dir = home.path().join(".config/systemd/user");
        assert_eq!(
            report.unit_files,
            vec![
                dir.join("ovp2-scheduler.service"),
                dir.join("ovp2-scheduler.timer")
            ]
        );
        assert!(dir.join("ovp2-scheduler.service").exists());
        assert!(dir.join("ovp2-scheduler.timer").exists());
        let calls = runner.calls.borrow();
        assert_eq!(
            *calls,
            vec![
                "systemctl --user daemon-reload".to_string(),
                "systemctl --user enable --now ovp2-scheduler.timer".to_string(),
            ]
        );
    }

    #[test]
    fn install_fails_loud_when_load_fails() {
        let home = tempfile::tempdir().unwrap();
        let vault = tempfile::tempdir().unwrap();
        let mut c = cfg();
        c.vault_root = vault.path().to_path_buf();
        c.env_file = vault.path().join(".ovp/daily.env");
        let runner = FakeRunner {
            fail_all: true,
            ..Default::default()
        };
        let err = install_with(&c, Flavor::Launchd, home.path(), &runner).unwrap_err();
        assert!(format!("{err}").contains("launchctl load"), "got: {err}");
    }

    #[test]
    fn uninstall_removes_units_but_leaves_env_and_logs() {
        let home = tempfile::tempdir().unwrap();
        let vault = tempfile::tempdir().unwrap();
        let mut c = cfg();
        c.vault_root = vault.path().to_path_buf();
        c.env_file = vault.path().join(".ovp/daily.env");
        let runner = FakeRunner::default();
        install_with(&c, Flavor::Systemd, home.path(), &runner).unwrap();
        let log = c.log_path(Flavor::Systemd);
        std::fs::write(&log, "ran\n").unwrap();

        let removed = uninstall_with(Flavor::Systemd, home.path(), &runner).unwrap();

        assert_eq!(removed.len(), 2);
        assert!(!removed[0].exists() && !removed[1].exists());
        assert!(c.env_file.exists(), "env file must survive uninstall");
        assert!(log.exists(), "logs must survive uninstall");
        let calls = runner.calls.borrow();
        assert!(calls.contains(&"systemctl --user disable --now ovp2-scheduler.timer".to_string()));
        assert_eq!(calls.last().unwrap(), "systemctl --user daemon-reload");
    }

    #[test]
    fn uninstall_when_nothing_installed_is_a_clean_noop() {
        let home = tempfile::tempdir().unwrap();
        let runner = FakeRunner::default();
        assert!(
            uninstall_with(Flavor::Launchd, home.path(), &runner)
                .unwrap()
                .is_empty()
        );
        assert!(
            runner.calls.borrow().is_empty(),
            "no launchctl calls for a no-op"
        );
    }
}
