"""Tests for M20 / BL-076 task dispatcher."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from ovp_pipeline.commands.task_dispatch import (
    DispatchError,
    NoHandlerError,
    RateLimitedError,
    TaskContext,
    TaskResult,
    dispatch_task,
    list_pending_tasks,
    main,
    parse_task_filename,
    register_handler,
)


# ── Fixtures ─────────────────────────────────────────────────────


class _FakeLLM:
    def __init__(self, response: str = "stub response", *,
                 capture: list[tuple[str, str]] | None = None) -> None:
        self.response = response
        self.calls: list[tuple[str, str]] = capture if capture is not None else []

    def call(self, system_prompt: str, user_prompt: str,
             max_tokens: int = 0) -> str:
        self.calls.append((system_prompt, user_prompt))
        return self.response


def _make_vault(tmp_path: Path) -> Path:
    vault = tmp_path / "vault"
    (vault / "50-Inbox" / "02-Tasks").mkdir(parents=True)
    (vault / "40-Resources" / "Generated").mkdir(parents=True)
    (vault / "70-Archive" / "tasks").mkdir(parents=True)
    (vault / "60-Logs").mkdir(parents=True)
    return vault


def _write_task(vault: Path, name: str, body: str = "test task body") -> Path:
    p = vault / "50-Inbox" / "02-Tasks" / name
    p.write_text(body, encoding="utf-8")
    return p


# ── parse_task_filename ─────────────────────────────────────────


def test_parse_task_filename_extracts_prefix_and_slug():
    assert parse_task_filename("RESEARCH-claude-code-mcp.md") == (
        "RESEARCH", "claude-code-mcp"
    )
    assert parse_task_filename("SYNTHESIZE-x.md") == ("SYNTHESIZE", "x")


def test_parse_task_filename_rejects_non_matching():
    assert parse_task_filename("README.md") is None
    assert parse_task_filename("notes.md") is None
    assert parse_task_filename("lowercase-prefix.md") is None
    assert parse_task_filename("RESEARCH.md") is None


# ── dispatch_task happy path ─────────────────────────────────────


def test_dispatch_research_writes_output_and_archives(tmp_path: Path):
    vault = _make_vault(tmp_path)
    task = _write_task(vault, "RESEARCH-vector-search.md", "operator note\n")

    llm = _FakeLLM("# Core insight\n\nVector search is X.\n")
    out = dispatch_task(vault, task, llm_client=llm)

    # Output written to 40-Resources/Generated/YYYY-MM/
    assert out.exists()
    assert "Vector search is X." in out.read_text(encoding="utf-8")
    # Footer appended.
    assert "Generated by RESEARCH handler" in out.read_text(encoding="utf-8")
    # Original task archived (not still in 02-Tasks/).
    assert not task.exists()
    assert any((vault / "70-Archive" / "tasks").rglob("RESEARCH-*.md"))
    # Audit event written.
    pipeline_log = (vault / "60-Logs" / "pipeline.jsonl").read_text(encoding="utf-8")
    assert "task_dispatched" in pipeline_log
    # Rate-limit ledger written.
    rl_log = (vault / "60-Logs" / "task-dispatch.jsonl").read_text(encoding="utf-8")
    assert "RESEARCH" in rl_log


def test_dispatch_passes_user_context_when_present(tmp_path: Path):
    vault = _make_vault(tmp_path)
    (vault / "OVP_RULES.md").write_text(
        "# Rules\nNever delete.\n", encoding="utf-8",
    )
    task = _write_task(vault, "SYNTHESIZE-memory.md", "scope\n")

    llm = _FakeLLM("synth result")
    dispatch_task(vault, task, llm_client=llm)

    sys_prompt, _ = llm.calls[0]
    # USER.md absent, RULES present → only the rules block is injected.
    assert "Autonomous Action Rules" in sys_prompt
    assert "Never delete." in sys_prompt
    # Handler's own system prompt still concatenated below.
    assert "synthesis handler" in sys_prompt.lower()


def test_dispatch_no_context_when_files_missing(tmp_path: Path):
    vault = _make_vault(tmp_path)
    task = _write_task(vault, "CONTRADICT-foo.md")

    llm = _FakeLLM("contradiction body")
    dispatch_task(vault, task, llm_client=llm)

    sys_prompt, _ = llm.calls[0]
    assert "Autonomous Action Rules" not in sys_prompt
    assert "User Profile" not in sys_prompt
    # Handler prompt itself present.
    assert "contradiction-sweep handler" in sys_prompt.lower()


# ── error paths ─────────────────────────────────────────────────


def test_dispatch_unknown_prefix_raises_no_handler(tmp_path: Path):
    vault = _make_vault(tmp_path)
    task = _write_task(vault, "FOO-bar.md")
    with pytest.raises(NoHandlerError):
        dispatch_task(vault, task, llm_client=_FakeLLM())
    # Task stays in place when no handler exists.
    assert task.exists()


def test_dispatch_bad_filename_raises_no_handler(tmp_path: Path):
    vault = _make_vault(tmp_path)
    task = _write_task(vault, "lowercase-name.md")
    with pytest.raises(NoHandlerError):
        dispatch_task(vault, task, llm_client=_FakeLLM())


def test_dispatch_handler_exception_audited(tmp_path: Path):
    vault = _make_vault(tmp_path)

    def _boom(ctx: TaskContext) -> TaskResult:
        raise RuntimeError("handler exploded")

    register_handler("BOOM", _boom, "test only")
    task = _write_task(vault, "BOOM-stuff.md")
    with pytest.raises(DispatchError):
        dispatch_task(vault, task, llm_client=_FakeLLM())

    # task_failed event recorded.
    pipeline_log = (vault / "60-Logs" / "pipeline.jsonl").read_text(encoding="utf-8")
    assert "task_failed" in pipeline_log
    # Original task NOT archived (handler failed before archival).
    assert task.exists()


# ── rate limiting ───────────────────────────────────────────────


def test_rate_limit_blocks_after_cap(tmp_path: Path):
    vault = _make_vault(tmp_path)
    llm = _FakeLLM()

    # Cap at 2 — dispatch two, third must raise.
    t1 = _write_task(vault, "RESEARCH-one.md")
    t2 = _write_task(vault, "RESEARCH-two.md")
    t3 = _write_task(vault, "RESEARCH-three.md")
    dispatch_task(vault, t1, llm_client=llm, rate_limit=2)
    dispatch_task(vault, t2, llm_client=llm, rate_limit=2)
    with pytest.raises(RateLimitedError):
        dispatch_task(vault, t3, llm_client=llm, rate_limit=2)

    # Third file untouched in the queue.
    assert t3.exists()
    # task_rate_limited event recorded.
    pipeline_log = (vault / "60-Logs" / "pipeline.jsonl").read_text(encoding="utf-8")
    assert "task_rate_limited" in pipeline_log


# ── list_pending_tasks ──────────────────────────────────────────


def test_list_pending_skips_non_matching_files(tmp_path: Path):
    vault = _make_vault(tmp_path)
    _write_task(vault, "RESEARCH-a.md")
    _write_task(vault, "SYNTHESIZE-b.md")
    _write_task(vault, "README.md")              # ignored
    _write_task(vault, "notes-on-stuff.md")      # ignored

    pending = list_pending_tasks(vault)
    names = sorted(p.name for p in pending)
    assert names == ["RESEARCH-a.md", "SYNTHESIZE-b.md"]


# ── CLI surface ─────────────────────────────────────────────────


def test_cli_list_handlers(capsys):
    rc = main(["--vault-dir", "/tmp", "--list-handlers"])
    assert rc == 0
    out = capsys.readouterr().out
    for prefix in ("RESEARCH", "SYNTHESIZE", "CONTRADICT"):
        assert prefix in out


def test_cli_requires_action(capsys, tmp_path: Path):
    vault = _make_vault(tmp_path)
    with pytest.raises(SystemExit):
        main(["--vault-dir", str(vault)])
